version: '3.3'
services:
  curator-support-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curator-support-web
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CURATOR_SUPPORT_CONFIG_PATH=.configs/app.docker.toml
    command: sh -c "python -m src.curator_support.main.web"
    depends_on:
      - pgsql
      - db_migration
      - redis

  curator-support-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curator-support-bot
    restart: always
    environment:
      - CURATOR_SUPPORT_CONFIG_PATH=.configs/app.docker.toml
    command: sh -c "python -m src.curator_support.main.bot"
    depends_on:
      - pgsql
      - db_migration
      - redis

  db_migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_migration
    restart: "on-failure"
    environment:
      - CURATOR_SUPPORT_CONFIG_PATH=.configs/app.docker.toml
    depends_on:
      - pgsql
    command: sh -c "python -m alembic upgrade head"

  pgsql:
    image: postgres:16.0-alpine3.18
    container_name: pgsql
    ports:
      - "5432:5432"
    env_file:
      - .configs/db.env
    volumes:
      - /curator-support/postgresql/data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2.4-alpine
    container_name: "redis"
    restart: "unless-stopped"
    volumes:
      - "/hotel-bot/redis/config:/usr/local/etc/redis"
      - "/hotel-bot/redis/data:/data"
    ports:
      - "6379:6379"
    command: "redis-server"